general:
    folder_output: outputs/L2_studies
    fname_output: iea15mw
    
design_variables:
  floating:
        joints:
            flag: True
            r_coordinate:
                - names: [col1_keel, col1_freeboard, col2_keel, col2_freeboard, col3_keel, col3_freeboard]
                  lower_bound: 36.
                  upper_bound: 66.
        members:
            flag: True
            groups:
                - names: [main_column]
                  ballast:
                      lower_bound: 350
                      upper_bound: 650
                - names: [column1,column2,column3]
                  ballast:
                      lower_bound: 350
                      upper_bound: 650

constraints:
  tower:
    height_constraint:
      flag: False
      lower_bound: 0.01
      upper_bound: 0.01
    stress:
      flag: False
    global_buckling:
      flag: False
    shell_buckling:
      flag: False
  floating:
        buoyancy:
            flag: False
        fixed_ballast_capacity:
            flag: False
        variable_ballast_capacity:
            flag: False
        metacentric_height:
            flag: False
  control:
    rotor_overspeed:
      flag: False
      max: 0.2
    Max_PtfmPitch:
      flag: False
      max: 6

merit_figure: weis_lcoe

driver:
  optimization:
    flag: True     # Flag to enable optimization
    solver: LN_COBYLA
    max_iter: 100
  design_of_experiments:
    flag: False          # Flag to enable design of experiments
    run_parallel: True    # Flag to run using parallel processing
    generator: FullFact   # Type of input generator. (Uniform)
    num_samples: 5      # number of samples for (Uniform only)

recorder:
    flag: True             # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
    just_dvs: True          
