name: CI_rosco-toolbox

# We run CI on push commits on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
        python-version: ["3.8"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: "latest"
          channels: conda-forge, general
          auto-update-conda: true
          python-version: 3.8
          environment-file: environment.yml

      # Install compilers
      - name: Add dependencies linux
        if: false == contains( matrix.os, 'windows')
        shell: pwsh
        run: |
          conda install -y compilers

      - name: Add dependencies windows 
        if: true == contains( matrix.os, 'windows')
        shell: bash -l {0}
        run: |
          conda install -y m2w64-toolchain

      # Install ROSCO linux
      - name: Compile ROSCO linux
        if: false == contains( matrix.os, 'windows')
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake ..
          make install

      # Install ROSCO windows
      - name: Compile ROSCO windows
        if: true == contains( matrix.os, 'windows')
        shell: pwsh
        run: |
          mkdir build
          cd build
          cmake .. -G "MinGW Makefiles" 
          make install
          
