general:
    folder_output: outputs/12_linearization
    fname_output: iea15mw
    
design_variables:
  tower:
    rho:
      flag: False
      lower_bound: 5000.
      upper_bound: 10000.
    E:
      flag: False
      lower_bound: 100.e9
      upper_bound: 300.e9

driver:
  optimization:
    flag: False           # Flag to enable optimization
  design_of_experiments:
    flag: False            # Flag to enable design of experiments
    run_parallel: False    # Flag to run using parallel processing
    generator: FullFact    # Type of input generator. (Uniform)
    num_samples: 2        # number of samples for (Uniform only)

recorder:
    flag: True             # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
    just_dvs: True          
