general:
    folder_output: pitch_opt
    fname_output: iea15mw
design_variables:
  control:
    servo:
      pitch_control:
        flag: True
        omega_min: 0.1
        omega_max: 0.7
        zeta_min: 0.4
        zeta_max: 3.0

merit_figure: DEL_TwrBsMyt  # Merit figure of the optimization problem. The options are 'AEP' - 'LCOE' - 'Cp' - 'blade_mass' - 'blade_tip_deflection'

constraints:
  control:
    rotor_overspeed:
      flag: True
      min: 0.0
      max: 0.2

driver:
  optimization:
    flag: True
    tol: 1.e-2            # Optimality tolerance
    max_major_iter: 2     # Maximum number of major design iterations (SNOPT)
    max_minor_iter: 100   # Maximum number of minor design iterations (SNOPT)
    max_iter: 1          # Maximum number of iterations (SLSQP)
    solver: SLSQP         # Optimization solver. Other options are 'SLSQP' - 'CONMIN'
    step_size: 1.e-3      # Step size for finite differencing
    form: central         # Finite differencing mode, either forward or central

recorder:
    flag: False             # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
