!     -*- f90 -*-
!     This file is autogenerated with f2py (version:1.21.5)
!     It contains Fortran 90 wrappers to fortran functions.

      
      subroutine f2pyinithams_lib(f2pysetupfunc)
      use hams_lib, only : exec
      external f2pysetupfunc
      call f2pysetupfunc(exec)
      end subroutine f2pyinithams_lib


