'''This is the page for visualize the WEIS inputs in 3D simulation model'''

import dash_bootstrap_components as dbc
from dash import html, register_page, callback, Input, Output, dcc
import pandas as pd
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go
from dash.exceptions import PreventUpdate
from weis.visualization.utils import empty_figure

import vtk
import dash_vtk
from dash_vtk.utils import to_mesh_state

register_page(
    __name__,
    name='WindIO',
    top_nav=True,
    path='/windio'
)

def render_mesh():
    # Read STL file generated by WindIO Tool
    stl_file_path = '/Users/sryu/Desktop/FY24/windio2cad/nrel5mw-semi_oc4.stl'
    # stl_file_path = '/Users/sryu/Desktop/FY24/ACDC/project1/case01/vtk/01_NREL_5MW-ED.Mode1.LinTime1.ED_BladeLn2Mesh_motion1.010.vtp'
    # reader = vtk.vtkUnstructuredGridReader()  # Doesn't work for both
    # reader = vtk.vtkXMLPolyDataReader()     # Able to read vtp file, but doesn't work with stl file
    reader = vtk.vtkSTLReader()
    reader.SetFileName(stl_file_path)
    reader.Update()

    # Get dataset and build a mesh structure to pass it as a Mesh
    dataset = reader.GetOutput()
    mesh_state = to_mesh_state(dataset)

    # print('mesh state: ', mesh_state)

    content = dash_vtk.View([
        dash_vtk.GeometryRepresentation([
            dash_vtk.Mesh(state=mesh_state)
        ])
    ])

    return content


# We are using card container where we define sublayout with rows and cols.
def layout():

    content = render_mesh()

    layout = html.Div(
        style={'width':'100%', 'height':'600px'},
        children=[content]
    )

    return layout