general:
    folder_output: newOF1
    fname_output: BAR_0_output
design_variables:
  blade:
    aero_shape:
      twist:
        flag: False  # Flag to optimize the twist
        inverse: False # Flag to determine twist from the user-defined desired margin to stall (defined in constraints)
        n_opt: 20     # Number of control points along blade span
        lower_bound: [0.26183354, 0.2230693, 0.18158914, 0.13477374, 0.07618275, 0.02795962, 0.01146387, 0.00617178, 0.00127423, -0.0052858, -0.01278764, -0.02249582, -0.03758844, -0.05534088, -0.07038717, -0.08335621, -0.09570016, -0.10806486, -0.12024473, -0.13221456]         # Lower bounds for the twist in [rad] at the n_opt locations
        upper_bound: [0.43636646, 0.39760223, 0.35612206, 0.30930667, 0.25071568, 0.20249254, 0.18599679, 0.18070471, 0.17580715, 0.16924712, 0.16174529, 0.1520371, 0.13694449, 0.11919205, 0.10414576, 0.09117671, 0.07883277, 0.06646807, 0.0542882, 0.04231837] # Upper bounds for the twist in [rad] at the n_opt locations
        lock_root: 4
        lock_tip: 0
      chord:
        flag: False     # Flag to optimize the chord
        n_opt: 20        # Number of control points along blade span
        min_gain: 0.2   # Nondimensional lower bound at the n_opt locations
        max_gain: 5.0   # Nondimensional upper bound at the n_opt locations
        lock_root: 4
        lock_tip: 0

merit_figure: Cp  # Merit figure of the optimization problem. The options are 'AEP' - 'LCOE' - 'Cp' - 'blade_mass' - 'blade_tip_deflection'

constraints:
  blade:
    strains_spar_cap_ss:
      flag: False     # Flag to impose constraints on maximum strains (absolute value) in the spar cap on the blade suction side
      max:  3500.e-6  # Value of maximum strains [-]
    strains_spar_cap_ps:
      flag: False     # Flag to impose constraints on maximum strains (absolute value) in the spar cap on the blade pressure side
      max:  3500.e-6  # Value of maximum strains [-]
    tip_deflection:
      flag: False     # Constraint that maximum tip deflection cannot exceed 70% of tower clearance. Only for upwind rotors
    stall:
      flag: False     # Constraint on minimum stall margin
      margin: 0.05233 # Value of minimum stall margin in [rad]
    chord:
      flag: False # Constraint on maximum chord
      max: 4.75   # Value of maximum chord in [m]

driver:
    optimization:
      flag: True
      tol: 1.e-3            # Optimality tolerance
      max_major_iter: 10    # Maximum number of major design iterations (SNOPT)
      max_minor_iter: 100   # Maximum number of minor design iterations (SNOPT)
      max_iter: 20          # Maximum number of iterations (SLSQP)
      solver: SNOPT         # Optimization solver. Other options are 'SLSQP' - 'CONMIN'
      step_size: 1.e-3      # Step size for finite differencing
      form: central         # Finite differencing mode, either forward or central

recorder:
    flag: True              # Flag to activate OpenMDAO recorder
    file_name: log_opt.sql  # Name of OpenMDAO recorder
