name: CI_MoorPy

# We run CI on push commits and pull requests on all branches
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    build_pip:
        name: Pip Build (${{ matrix.os }}) - ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash -l {0}
                
        strategy:
            fail-fast: false #true
            matrix:
                os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
                python-version: ["3.9", "3.10", "3.11"]

        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v4
              id: cp
              with:
                  python-version: ${{ matrix.python-version }}
                  update-environment: true

            - name: Pip Install MoorPy
              run: |
                  '${{ steps.cp.outputs.python-path }}' -m pip install -vv -e .[test]

            - name: Test run
              run: |
                  cd tests
                  '${{ steps.cp.outputs.python-path }}' -m pytest .


    build_conda:
        name: Conda Build (${{ matrix.os }}) - ${{ matrix.python-version }}
        runs-on: ${{ matrix.os }}
        defaults:
            run:
                shell: bash -l {0}
                
        strategy:
            fail-fast: false
            matrix:
                os: ["ubuntu-latest", "macOS-latest", "windows-latest"]
                python-version: ["3.9", "3.10", "3.11"]

        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - uses: conda-incubator/setup-miniconda@v2
              # https://github.com/marketplace/actions/setup-miniconda
              with:
                  miniconda-version: "latest"
                  auto-update-conda: true
                  python-version: ${{ matrix.python-version }}
                  environment-file: environment.yml
                  channels: conda-forge
                  activate-environment: test
                  auto-activate-base: false

            # Install 
            - name: Conda Install MoorPy
              run: |
                  python -m pip install -e . -vv

            - name: Test run
              run: |
                  cd tests
                  pytest .

